# Generated by Django 5.2 on 2025-04-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rezerwacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoba', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('godzina', models.TimeField()),
                ('czas', models.TimeField()),
                ('notatka', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezerwacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='rezerwacje.rezerwacje')),
            ],
        ),
    ]
