# Generated by Django 5.2 on 2025-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='cola',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='fuzetea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='jack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='jager',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='piwo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='rodzaj_platnosci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='sok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='tiger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='woda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkty',
            name='zubr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='kwota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='rodzaj_platnosci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='rodzaj_rezerwacji',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='zatwierdzony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='notatka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
