# Generated by Django 5.2 on 2025-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0003_alter_rezerwacje_rodzaj_rezerwacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacje',
            name='ilosc_osob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
