# Generated by Django 5.2 on 2025-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0004_rezerwacje_ilosc_osob'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacje',
            name='cola',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='fuzetea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='jack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='jager',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='piwo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='produkty_platnosc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='tarczyn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='tiger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='woda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='zubr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='produkty',
        ),
    ]
