# Generated by Django 5.2 on 2025-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0005_rezerwacje_cola_rezerwacje_fuzetea_rezerwacje_jack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacje',
            name='osoba',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
