# Generated by Django 5.2 on 2025-05-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0006_alter_rezerwacje_osoba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacje',
            name='cola',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='fuzetea',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='ilosc_osob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='jack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='jager',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='kwota',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='piwo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='produkty_platnosc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='rodzaj_platnosci',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='tarczyn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='tiger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='woda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='zatwierdzony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezerwacje',
            name='zubr',
            field=models.IntegerField(default=0),
        ),
    ]
