# Generated by Django 5.2 on 2025-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0007_alter_rezerwacje_cola_alter_rezerwacje_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerwacje',
            old_name='zatwierdzony',
            new_name='zatwierdzono',
        ),
    ]
